### ISSUE TITLE
org.freedesktop.PolicyKit1: Cannot launch daemon, file not found or permissions invalid (23)

### ISSUE THREAD

**Issue by rubyFeedback** [timlau/gtk4-python#1]
Not sure if you want to fix it, perhaps a message can be printed what to do next
e. g. what to install here to make this work.

    loading custom styling : main.css
    Traceback (most recent call last):
      File "/Depot/j/gtk4-python/main.py", line 760, in do_activate
        win = MyWindow("My Gtk4 Application", 800, 800, application=self)
      File "/Depot/j/gtk4-python/main.py", line 289, in __init__
        self.page1 = self.setup_page_one('page1', 'Page 1')
      File "/Depot/j/gtk4-python/main.py", line 349, in setup_page_one
        lock_btn = Gtk.LockButton.new(get_permision())
      File "/Depot/j/gtk4-python/main.py", line 41, in get_permision
        prem = Polkit.Permission.new_sync(action_id, None, None)
    gi.repository.GLib.GError: g-dbus-error-quark: Error initializing authority: Error calling StartServiceByName for         org.freedesktop.PolicyKit1: Cannot launch daemon, file not found or permissions invalid (23)

**Comment by timlau** [comment]
LockButton need an active polkit installation and the Dbus daemon org.freedesktop.PolicyKit1 running
I have only tested the code on Fedora Workstation 34 and later, but other distribution might work or not.

If you don't need the lock button, then just comment  these lines out.
https://github.com/timlau/gtk4-python/blob/01a2a59cd78cdcc40642cfe3a1e3b960469a1b2a/main.py#L349-L353

This is only demo code to show how to use different gtk4 widgets from Python, so I will not build error handling into the code.
